version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-users
        - backend-feeds
  backend-user:
    image: phucpn/udagram-api-user:latest
    environment:
      POSTGRES_USERNAME: $POSTGRESS_USERNAME
      POSTGRES_PASSWORD: $POSTGRESS_PASSWORD 
      POSTGRES_DB: $POSTGRESS_DB 
      POSTGRES_HOST: $POSTGRESS_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: phucpn/udagram-api-feed:latest
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRESS_USERNAME
      POSTGRES_PASSWORD: $POSTGRESS_PASSWORD 
      POSTGRES_DB: $POSTGRESS_DB
      POSTGRES_HOST: $POSTGRESS_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: phucpn/udagram-frontend:latest
    ports:
      - "8100:80"