# .circleci/config.yml file
version: 2.1

jobs:
  build:            # job name
    docker:         # executor type
      - image: cimg/base:current # Docker image that installs Docker and has Git,
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: echo "No need to install anything. \n Just build and push the Docker image."
      - run:
          name: Build and push Docker image
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version # print the version for logging
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t reverseproxy ./udagram-reverseproxy
            docker build -t udagram-frontend ./udagram-frontend

            docker tag udagram-api-feed phucpn/udagram-api-feed:latest
            docker tag udagram-api-user phucpn/udagram-api-user:latest
            docker tag reverseproxy phucpn/reverseproxy:latest
            docker tag udagram-frontend phucpn/udagram-frontend:latest
            
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push phucpn/udagram-api-feed:latest
            docker push phucpn/udagram-api-user:latest
            docker push phucpn/reverseproxy:latest
            docker push phucpn/udagram-frontend:latest
